---
# tasks file for apigee-opdk-settings-management-server
- name: Normalized name for management server local ip if on dc-1
  set_fact:
    cacheable: yes
    local_mgmt_ip: "{{ hostvars[groups['dc_1_ms'][0]]['private_address'] }}"
  when: groups['dc-1'] is defined and groups['dc_1_ms'] is defined and inventory_hostname in groups['dc-1'] and hostvars[groups['dc_1_ms'][0]]['private_address'] is defined

- name: Normalized name for management server local ip if on dc-2
  set_fact:
    cacheable: yes
    local_mgmt_ip: "{{ hostvars[groups['dc_2_ms'][0]]['private_address'] }}"
  when: groups['dc-2'] is defined and groups['dc_2_ms'] is defined and inventory_hostname in groups['dc-2'] and hostvars[groups['dc_1_ms'][0]]['private_address'] is defined

- name: Normalized name for management server local ip to dc-1 if current node is not on dc-1 or dc-2
  set_fact:
    cacheable: yes
    local_mgmt_ip: "{{ hostvars[groups['dc_1_ms'][0]]['private_address'] }}"
  when: local_mgmt_ip is not defined or local_mgmt_ip | trim | length == 0

- name: Cache ms port
  set_fact:
    cacheable: yes
    ms_port: "{{ ms_port }}"